#!/bin/bash

echo "🔍 API错误诊断工具"
echo "==================="

echo ""
echo "📋 从Render日志看到的403错误可能原因:"
echo "1. 飞书API权限问题 - token过期或权限不足"
echo "2. GitHub API权限问题 - token权限不足"
echo "3. Google Maps API配额问题 - 超出免费限制"
echo ""

echo "🧪 诊断步骤建议:"
echo "=================="

echo ""
echo "步骤1: 检查飞书API配置"
echo "-------------------"
echo "- 检查FEISHU_APP_ID, FEISHU_APP_SECRET是否正确"
echo "- 检查FEISHU_APP_TOKEN, FEISHU_TABLE_ID是否有效"
echo "- 确认飞书应用权限包含多维表格访问权限"
echo ""

echo "步骤2: 检查GitHub API配置" 
echo "----------------------"
echo "- 检查GITHUB_TOKEN是否有效且有写入权限"
echo "- 确认token权限包含repo完整访问权限"
echo "- 检查GITHUB_REPO_OWNER, GITHUB_REPO_NAME是否正确"
echo ""

echo "步骤3: 检查Google Maps API配置"
echo "---------------------------"
echo "- 检查GOOGLE_MAPS_API_KEY是否有效"
echo "- 确认API配额是否充足"
echo "- 检查API调用限制设置"
echo ""

echo "🔧 快速修复建议:"
echo "================"
echo ""
echo "临时修复方案1: 禁用路线优化功能"
echo "-----------------------------"
echo "如果Google Maps API有问题，可以临时注释掉GOOGLE_MAPS_API_KEY环境变量"
echo "这样系统会跳过路线优化功能，但数据同步依然可以正常工作"
echo ""

echo "临时修复方案2: 增加API错误处理"
echo "----------------------------"
echo "在代码中增加更详细的错误处理和降级机制"
echo ""

echo "永久修复方案: 检查和更新API配置"
echo "----------------------------"
echo "1. 登录飞书开发者平台检查应用状态"
echo "2. 登录GitHub检查Personal Access Token状态"  
echo "3. 登录Google Cloud Console检查Maps API配额"
echo ""

echo "📞 如需技术支持，请提供:"
echo "======================"
echo "1. Render完整错误日志"
echo "2. 飞书应用配置截图"
echo "3. GitHub token权限截图"
echo "4. Google Maps API配额截图" 